### ISSUE TITLE
Enable travis-ci for pull requests.

### ISSUE THREAD

**Issue by nnathan** [fgimian/easysnmp#10]
It would be nice to have pull requests be tested against travis-ci.

**Comment by fgimian** [comment]
These are actually enabled buddy:

![image](https://cloud.githubusercontent.com/assets/1811813/7960782/6d8d11b2-0a46-11e5-8ebe-6cad86f1f98e.png)

Here's the Travis build for your pull request:

https://travis-ci.org/fgimian/easysnmp/builds/65228149

Cheers
Fotis
