### ISSUE TITLE
MAC address displaying in binary

### ISSUE THREAD

**Issue by nnathan** [fgimian/easysnmp#14]
I am lodging this issue on behalf of someone else.

Below I'm querying a standard Cisco device for the MAC addresses of each interface, all MIBs enabled.

```bash
$ cat ~/.snmp/snmp.conf
mibs +ALL
$ snmpwalk  -On -v2c -c public redacted ifPhysAddress
.1.3.6.1.2.1.2.2.1.6.1 = STRING: 7c:ad:74:f1:84:0
.1.3.6.1.2.1.2.2.1.6.2 = STRING: 7c:ad:74:f1:84:1
.1.3.6.1.2.1.2.2.1.6.3 = STRING:
.1.3.6.1.2.1.2.2.1.6.4 = STRING:
.1.3.6.1.2.1.2.2.1.6.5 = STRING: 7c:ad:74:f1:84:0
.1.3.6.1.2.1.2.2.1.6.6 = STRING: 7c:ad:74:f1:84:0
.1.3.6.1.2.1.2.2.1.6.7 = STRING: 7c:ad:74:f1:84:1
```

With MIBs disabled:

```bash
$ mv ~/.snmp ~/.snmp.bak
$ snmpwalk -m'' -On -v2c -c public redacted .1.3.6.1.2.1.2.2.1.6
.1.3.6.1.2.1.2.2.1.6.1 = Hex-STRING: 7C AD 74 F1 84 00
.1.3.6.1.2.1.2.2.1.6.2 = Hex-STRING: 7C AD 74 F1 84 01
.1.3.6.1.2.1.2.2.1.6.3 = ""
.1.3.6.1.2.1.2.2.1.6.4 = ""
.1.3.6.1.2.1.2.2.1.6.5 = Hex-STRING: 7C AD 74 F1 84 00
.1.3.6.1.2.1.2.2.1.6.6 = Hex-STRING: 7C AD 74 F1 84 00
.1.3.6.1.2.1.2.2.1.6.7 = Hex-STRING: 7C AD 74 F1 84 01
```

Note the latter represents the MAC address as a Hex String. I believe SNMP is not processing the "textual convention" (I'll explain this soon) and showing the raw data in hex form.

Easysnmp doesn't honour the textual conventions when MIBs are loaded.

```python
In [46]: v = snmp_get(('ifPhysAddress', 1), hostname='redacted', community='public', version=2)

# this is the binary representation of the MAC address bytes
In [48]: v.value
Out[48]: u'|\xadt\xf1\x84\x00'

# convert into a hex string separated by :
In [49]: ':'.join('{:02x}'.format(ord(x)) for x in v.value)
Out[49]: '7c:ad:74:f1:84:00'
```

The reason `snmpwalk` displayed it as a STRING in the standard convention is because it is defined this way in the MIBs:

```bash
$ snmptranslate -On -Td IF-MIB::ifPhysAddress
.1.3.6.1.2.1.2.2.1.6
ifPhysAddress OBJECT-TYPE
  -- FROM       IF-MIB, RFC1213-MIB
  -- TEXTUAL CONVENTION PhysAddress
  SYNTAX        OCTET STRING
  DISPLAY-HINT  "1x:"
  MAX-ACCESS    read-only
  STATUS        current
  DESCRIPTION   "The interface's address at its protocol sub-layer.  For
            example, for an 802.x interface, this object normally
            contains a MAC address.  The interface's media-specific MIB
            must define the bit and byte ordering and the format of the
            value of this object.  For interfaces which do not have such
            an address (e.g., a serial line), this object should contain
            an octet string of zero length."
::= { iso(1) org(3) dod(6) internet(1) mgmt(2) mib-2(1) interfaces(2) ifTable(2) ifEntry(1) 6 }
```

The `PhysAddress` TEXTUAL CONVENTION is a MIB thing that appears to be honoured by both [pysnmp](http://pysnmp.sourceforge.net/) when [pysnmp-mibs](https://pypi.python.org/pypi/pysnmp-mibs/) are loaded and the standard NET-SNMP commands.

I'm not sure if this is something that could be sorted from the underlying C interface or in the Python side.

**Comment by fgimian** [comment]
Hey mate, as discussed, simply `set use_sprint_value=True` when creating your session.  However, I'll leave this issue open to discuss the possibility of making this the default behaviour.

**Comment by thebuthcer** [comment]
Thanks fgimian, nnathan raised this on behlaf of me, appreciate your guys help and great job with this project.

**Comment by fgimian** [comment]
After some further discussion with @nnathan, we have decided to leave this option disabled by default.  Please set the `use_sprint_value` explicitly when you create a session or call an easy function.

Closing this one :smile:
