### ISSUE TITLE
remote_port in session API not used

### ISSUE THREAD

**Issue by LaMi-** [fgimian/easysnmp#26]
Hi devs,

today I found out that in the original NetSNMP library the remote_port, which is meant to configure SNMP to contact devices on different ports than 161, is not used at all.

However, I recognized that specifying "hostaddress:port" as destination host made NetSNMP use the custom port.

From a quick look at your docs and interface.c I think the problem remains in Easy SNMP code. So I just wanted to let you know in case you like to make your library a bit better than the original one ;-)

I think this could be solved by implement handling the remote_port option or dropping that parameter and document the fact that the Session() parametere "hostname" might also contain a port specification.

**Comment by fgimian** [comment]
Hey there and thanks for your message.  I'm happy to tell you that this was a problem that I have already repaired in Easy SNMP.  In our version, the remote_port does wprk, would you like to give it a try?

The unit tests also use it as our test SNMP daemon runs on a non-standard port.

Cheers
Fotis

**Comment by LaMi-** [comment]
Nice one. Just another reason to seitch to Easy SNMP ;-). I'll give it a try soon.
