### ISSUE TITLE
easysnmp session.set problem

### ISSUE THREAD

**Issue by Dacicus** [fgimian/easysnmp#28]
Hi,

I have the following code:

        session = Session(hostname=Hostname, community=Community, version=2)
.................................................
        session.set('1.3.6.1.4.1.637.61.1.39.3.7.1.13.67108864', '2','i')

For the last line I get the error:
    session.set('.1.3.6.1.4.1.637.61.1.39.3.7.1.13.67108864', '2','i')
  File "/usr/lib64/python2.7/site-packages/easysnmp/session.py", line 351, in set
    success = interface.set(self, varlist)
easysnmp.exceptions.EasySNMPUndeterminedTypeError: a type could not be determine for the object

Thank you for your help.

**Comment by nnathan** [comment]
I think this is poor  documentation on our half, but can you try using `"INTEGER"` instead of `'i'` for the type?

Thanks.

**Comment by nnathan** [comment]
@fgimian: I've created a [small patch in a separate branch](https://github.com/nnathan/easysnmp/commit/0e39b601a99fc47eaa06ad5685e69dbd6f2827e0) to support `snmpset(1)` short types. Do you think this is something we should incorporate in the project? Secondly, should we do it in C or in the Python interface (before the `interface.set` is called)?

**Comment by Dacicus** [comment]
Hi,Thanks for the prompt response. It works with 'INTEGER'. I have a misunderstanding: how can I delete an object of type Session?
Best Regards,Octavian
 


     On Thursday, July 16, 2015 7:57 PM, Naveen Nathan <notifications@github.com> wrote:
   

 @fgimian: I've created a small patch in a separate branch to support snmpset(1) short types. Do you think this is something we should incorporate in the project? Secondly, should we do it in C or in the Python interface (before the interface.set is called)?—

**Comment by fgimian** [comment]
@Dacicus there's no need to delete the Session, it doesn't retain a persistent connection since SNMP is using SNMP and Python will garbage collect it as soon as it's out of scope.

Would you like to point me to your branch to check out?  I can provide further advice from there :smile: 

Thanks
fotis

**Comment by Dacicus** [comment]
I have no branch yet. I started learning python and test easysnmp library. So far I have worked in linux shell with NET-SNMP.
 
 Thanks for the helpOctavian
 


     On Friday, July 17, 2015 10:10 AM, Fotis Gimian <notifications@github.com> wrote:
   

 @Dacicus there's no need to delete the Session, it doesn't retain a persistent connection since SNMP is using SNMP and Python will garbage collect it as soon as it's out of scope.Would you like to point me to your branch to check out? I can provide further advice from there  Thanks
fotis—

**Comment by fgimian** [comment]
@Dacicus Apologies, I edited my message after I saved.  My question about the branch was actually meant towards @nnathan :smile:

**Comment by nnathan** [comment]
@fgimian: I disguised it as a hyperlink in my last message, but here it is again: https://github.com/nnathan/easysnmp/commit/0e39b601a99fc47eaa06ad5685e69dbd6f2827e0

**Comment by fgimian** [comment]
Thechanes look good @nnathan feel free to merge them in :smile:

**Comment by nnathan** [comment]
Changes are now merged and now `snmp_type` can be specified using the `snmpset(1)` short types: https://github.com/fgimian/easysnmp/pull/29.

**Comment by Dacicus** [comment]
How can I install/upgrade the easysnmp library that supports the short types in snmpset ?

Thank you,
Octavian

**Comment by nnathan** [comment]
Until a new minor version is released you can use the git version.

`pip install git+http://github.com/fgimian/easysnmp`
