### ISSUE TITLE
Upload to PyPi

### ISSUE THREAD

**Issue by renstrom** [fgimian/easysnmp#5]
Have you considered uploading a release to PyPi?

**Comment by fgimian** [comment]
Hey there @renstrom, thanks so much for your comment.  Absolutely! :smile: 

I'm working really hard on a first release as I'm still changing the API.  The final version will look something like this:

```python
from pynetsnmp import Session
session = Session(hostname='localhost', community='public', version=2)
system_description = session.get('sysDescr.0')
```

There won't be any needing to deal with Varbinds or VarLists at all :smile: 

Please bear with me, I'll probably need another week or two before it's been well tested and ready for release.  We have a heap of network gear in production and UAT to test against and I'd love to really run it through its paces before release.

Also the documentation (the README) is still unaltered and needs to be re-written along with possible publishing of docs to RTD.

Thanks so much for your interest, I'll be sure to post again when I release it on PyPi

Cheers
Fotis

**Comment by renstrom** [comment]
No worries, noticed you had some very recent activity and came here from a [StackOverflow](http://stackoverflow.com/questions/27631684/python-2-bindings-net-snmp-error-undefined-symbol-netsnmp-memdup). The official package is lacking to say the least, *especially* when it comes to installability! Good to see there is finally popping up an alternative :)

I will definitely be on the lookout for a release!

**Comment by fgimian** [comment]
Hey there, I've made huge progress on this library over the last few days and would like to invite you to test the first release with me.

Although the first release is not yet on PyPi, you may install it via pip as follows:

```bash
pip install git+https://github.com/fgimian/easysnmp.git@0.1
```

Documentation is now published at [Read the Docs](http://easysnmp.readthedocs.org/).

My friend Naveen and I would first like to make use of this library in our SNMP polling application and once we're a bit more confident of its stability and design, I'll release it on PyPI.

Cheers
Fotis

**Comment by fgimian** [comment]
I have decided to go ahead and release this on PyPi, you may find it [here](https://pypi.python.org/pypi/easysnmp/0.1).

More improvements and documentation on PyPi will come with the next version.

Cheers
Fotis
