### ISSUE TITLE
Convert snmp_get return value to string

### ISSUE THREAD

**Issue by StephanSchrenk** [fgimian/easysnmp#54]
Hello,
I am currently using "snmp_get" from easysnmp in Python!

First of all, the SNMP request works as it should, but I found out that the returned value is type "SNMPVariable" as you'll see here:
![error_snmpvariable](https://cloud.githubusercontent.com/assets/23398699/20211669/d40980ee-a7ff-11e6-8b79-60080870602a.png)

I used len() to find out whether it's a string so don't wonder..

Now my question is if there is any function to convert this returned type into a string so I can use the string manipulation of python! The aim is to get the temperature value only. (marked in red)
![snmp_return](https://cloud.githubusercontent.com/assets/23398699/20211859/bd445c02-a800-11e6-80a6-c240d7f97d45.PNG)

Here's the command I use to get the snmp information:
`snmp_get('1.3.6.1.4.1.21796.4.1.3.1.4.1', hostname='10.48.1.201', community='public', version=1)`

Thank you for your help!

Best regards,
Stephan Schrenk

**Comment by StephanSchrenk** [comment]
Update: via `type()` I found out that the data type seems to be "class 'easysnmp.variables.SNMPVariable'". Is there any way to convert this into a string?

**Comment by kamakazikamikaze** [comment]
You be able to retrieve the value using `.value`. For example,

```Python

from easysnmp import snmp_get

if __name__ == '__main__':
    response = snmp_get('1.3.6.1.4.1.21796.4.1.3.1.4.1', hostname='10.48.1.201', community='public', version=1)
    print response.value
```

Does that work?

**Comment by StephanSchrenk** [comment]
Very nice! Thank you, this simply accesses the object value, right?

**Comment by kamakazikamikaze** [comment]
Correct. Sorry for not replying sooner; I must've missed the email notification.

**Comment by fgimian** [comment]
Thanks for helping @kamakazikamikaze, closing this.

**Comment by devopsnetworks** [comment]
from easysnmp import snmp_get
session = {"hostname": '192.168.200.101',
           "community": 'pynetwork', "version": 2}

hostname = snmp_get('1.3.6.1.4.1.9.2.1.3.0', **session)

print(hostname.value)
