### ISSUE TITLE
easysnmp.exceptions.EasySNMPUnknownObjectIDError: unknown object id (sysLocation)

### ISSUE THREAD

**Issue by rfonacier** [fgimian/easysnmp#55]
I'm just new to python and SNMP.  I'm trying to follow:
https://pypi.python.org/pypi/easysnmp/0.2.3

**Command**
from easysnmp import Session
session = Session(hostname='localhost', community='public', version=2)
location = session.get('sysLocation.0')

**Error:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/easysnmp/session.py", line 315, in get
    interface.get(self, varlist)
easysnmp.exceptions.EasySNMPUnknownObjectIDError: unknown object id (sysLocation)

**Comment by kamakazikamikaze** [comment]
Do you have your snmp.conf file set up to load MIB files? If not, you need to manually specify the MIB where the OID is from (or specify the dot-notation value).

For example, if you receive the following from a terminal:
```
$ snmptranslate sysLocation.0
sysLocation.0: Unknown Object Identifier (Sub-id not found: (top) -> sysLocation)
```

Then the Net-SNMP library does not know where this OID is defined.

You could instead try the following:
```
$ snmptranslate SNMPv2-MIB::sysLocation.0
SNMPv2-MIB::sysLocation.0
$ snmptranslate SNMPv2-MIB::sysLocation.0 -On
.1.3.6.1.2.1.1.6.0
```

In Python:
```python
from easysnmp import Session
session = Session(hostname='localhost', community='public', version=2)
# Then either
location = session.get('SNMPv2-MIB::sysLocation.0')
# or
location = session.get('.1.3.6.1.2.1.1.6.0')
```

**Comment by rfonacier** [comment]
Thanks, @kamakazikamikaze. =)
