### ISSUE TITLE
easysnmp.exceptions.EasySNMPNoSuchNameError

### ISSUE THREAD

**Issue by rfonacier** [fgimian/easysnmp#57]
I have already installed EasySNMP.  But I am getting the error below when I try to use it.
Thanks in advance.

**Code :**
from easysnmp import snmp_get
snmp_get('1.3.6.1.2.1.1.5', hostname='192.168.254.3', community='public', version=2)

**Result :**
Python 3.4.2 (default, Oct 19 2014, 13:31:11) 
[GCC 4.9.1] on linux
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 
Traceback (most recent call last):
  File "/home/pi/Desktop/ronnie/test.py", line 3, in <module>
    snmp_get('1.3.6.1.2.1.1.5', hostname='192.168.254.3', community='public', version=2)
  File "/usr/local/lib/python3.4/dist-packages/easysnmp/easy.py", line 22, in snmp_get
    return session.get(oids)
  File "/usr/local/lib/python3.4/dist-packages/easysnmp/session.py", line 315, in get
    interface.get(self, varlist)
easysnmp.exceptions.EasySNMPNoSuchNameError: no such name error encountered

**Comment by kamakazikamikaze** [comment]
@rfonacier Just noticed this issue. Though I'm not a maintainer for the repo, I can try to help where I can.

Could you run the following in a terminal shell?

`snmpget -V`
`snmpget -v2c -c public 192.168.254.3 1.3.6.1.2.1.1.5`

What operating system is this being run on?

**Comment by kamakazikamikaze** [comment]
You're missing a `.0` at the end, e.g. `snmpget -v 2c -c public 192.168.254.3 1.3.6.1.2.1.1.5.0`

**Comment by rfonacier** [comment]
Thanks, kamakazikamikaze!
