### ISSUE TITLE
Installing EasySNMP on windows - encountering some error

### ISSUE THREAD

**Issue by rfonacier** [fgimian/easysnmp#58]
I'm trying to install EasySNMP but I'm getting some error.
Below is the command and result.
Thank you.

C:\Users\Ronnie>pip install easysnmp

Collecting easysnmp
  Using cached easysnmp-0.2.4.tar.gz
Installing collected packages: easysnmp
  Running setup.py install for easysnmp ... error
    Complete output from command c:\users\ronnie\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ronnie\\AppData\\Local\\Temp\\pip-build-es3m88_j\\easysnmp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ronnie\AppData\Local\Temp\pip-oyuhwisc-record\install-record.txt --single-version-externally-managed --compile:
    'net-snmp-config' is not recognized as an internal or external command,
    operable program or batch file.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\easysnmp
    copying easysnmp\compat.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\easy.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\exceptions.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\helpers.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\session.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\utils.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\variables.py -> build\lib.win32-3.6\easysnmp
    copying easysnmp\__init__.py -> build\lib.win32-3.6\easysnmp
    running build_ext
    building 'easysnmp.interface' extension
    creating build\temp.win32-3.6
    creating build\temp.win32-3.6\Release
    creating build\temp.win32-3.6\Release\easysnmp
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\ronnie\appdata\local\programs\python\python36-32\include -Ic:\users\ronnie\appdata\local\programs\python\python36-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tceasysnmp/interface.c /Fobuild\temp.win32-3.6\Release\easysnmp/interface.obj -Wno-unused-function
    cl : Command line error D8021 : invalid numeric argument '/Wno-unused-function'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\ronnie\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ronnie\\AppData\\Local\\Temp\\pip-build-es3m88_j\\easysnmp\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Ronnie\AppData\Local\Temp\pip-oyuhwisc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Ronnie\AppData\Local\Temp\pip-build-es3m88_j\easysnmp\

**Comment by kamakazikamikaze** [comment]
@rfonacier Sorry that I didn't see this sooner. Windows is currently not supported. I have tinkered in the past with getting it to work with VC but I was not able to make much progress.

If you are interested in looking into it, you can view the few commits I was able to make [in my Win32 branch.](https://github.com/kamakazikamikaze/easysnmp/tree/win32) However I must say that I am not confident that we can get it working.

**Comment by rfonacier** [comment]
Thanks, @kamakazikamikaze :)

**Comment by mokuq** [comment]
@kamakazikamikaze  Are you still not supporting Windows?

**Comment by Raanger99** [comment]
Hi from 2020!
As a first step, I built Net-SNMP 5.7.1 under Windows 10.
With the help of https://github.com/kamakazikamikaze/easysnmp/issues/32 and several minor fixes, I built and installed EasySNMP 0.2.5. But there's a strange issue with a simple test script I can't resolve.

`from easysnmp import Session
session = Session(hostname='10.1.7.130', community='public', version=2)
location = session.get('sysLocation.0')
print( location )
`
If I launch this script from command line, it doesn't work:

_C:\Python\eLearning>python easytest3.py
Traceback (most recent call last):
  File "easytest3.py", line 2, in <module>
    session = Session(hostname='10.1.7.130', community='public', version=2)
  File "C:\Python\lib\site-packages\easysnmp-0.2.5-py3.8-win-amd64.egg\easysnmp\session.py", line 280, in __init__
    self.sess_ptr = interface.session(
easysnmp.exceptions.EasySNMPConnectionError: couldn't create SNMP handle_

But, if I open and run the script in IDLE x64, everything works perfectly!
_=================== RESTART: C:\Python\eLearning\easytest3.py ==================
<SNMPVariable value='WP-106' (oid='sysLocation', oid_index='0', snmp_type='OCTETSTR')>
>>>_ 

Why is this difference between running a script from command line and from IDLE ? Any libraries, timeouts, settings, etc ?

Python 3.8.3 x64
MSVS Build Tools 2019
Windows 10
