### ISSUE TITLE
Different result on Pi Terminal and .PY file

### ISSUE THREAD

**Issue by rfonacier** [fgimian/easysnmp#60]
When I run this script on the Pi Terminal, I am getting a result but once I put in on .py file and run it, it doesn't give a result.

_**from easysnmp import snmp_get
snmp_get('iso.3.6.1.2.1.1.5.0', hostname='192.168.254.3', community='public',version=2)**_

Here's the screenshot of the Pi Terminal and the .py file with output.
![snmp_get no result](https://cloud.githubusercontent.com/assets/26764469/25835194/cd9fef98-348d-11e7-8050-1804b9e97a1e.png)

**Comment by kamakazikamikaze** [comment]
You're still receiving a result. The interpreter will print it out immediately. You'll need to manually print it, however, from your script.

Try this:

```python
from easysnmp import snmp_get

print("Start.")
print(snmp_get('iso.3.6.1.2.1.1.5.0', hostname='192.168.254.3', community='public', version=2))
#  As an alternative, save it to a variable and then print it
# result = snmp_get('iso.3.6.1.2.1.1.5.0', hostname='192.168.254.3', community='public', version=2)
# print(result)
print("Done.")
```

**Comment by rfonacier** [comment]
Thanks a lot @kamakazikamikaze for a prompt reply. =)
