### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by codekoala** [fgimian/easysnmp#7]
First off, this library is *excellent*!!! Thank you for overhauling the terrible official bindings.

The library works perfectly for me with Python 2.7.10, but ``interface.c`` doesn't compile for Python 3. Is there any chance that Python 3 support is on the roadmap?

**Comment by fgimian** [comment]
Hey there Josh, thanks for the kind words!  Yup, I was planning to try and support Python 3.x too since we will all inevitably be moving to it at some point sooner or later.

I'll give it a look soon to see what's involved and get back to you :smile: 

Cheers
Fotis

**Comment by codekoala** [comment]
Thanks for the quick response and good news. I can't wait :)

**Comment by fgimian** [comment]
I've just done an assessment on this and it looks like a considerable amount of work.  But I will try to give it a go soon.  I have managed to get the C interface to compile in Python 3.x but there are many problems which actually prevent it from functioning correctly in Python 3.x at this point in time.

I'll continue to update this issue as I make progress.

Cheers
Fotis

**Comment by codekoala** [comment]
Wonderful, thank you for the effort :)

**Comment by fgimian** [comment]
Hey there, great news!  I have a Python 3 compatible version working with only 6 unit tests failing (set_multiple doesn't work yet).  You're welcome to give it a try at https://github.com/fgimian/easysnmp/tree/python3

I have only tested against Python 3.4 at the moment but I plan to support 3.3 and 3.5 as well assuming they don't cause me any huge headaches :smile: 

Cheers
Fotis

**Comment by fgimian** [comment]
OK the last bug should now be fixed and we now have full compatibility with Python 3.2, 3.3 and 3.4 pending the test results here: https://travis-ci.org/fgimian/easysnmp/builds/64902934

This well be part of the next Easy SNMP release (v0.2).

Cheers
Fotis

**Comment by fgimian** [comment]
Hello again, [Easy SNMP 0.2 is now released on PyPI](https://pypi.python.org/pypi/easysnmp/0.2) and includes full support for Python 3.2, 3.3 and 3.4.

Please let me know how you go with it :smile: 
Fotis

**Comment by codekoala** [comment]
Wow, that was fast! I've tested it on my Python 3.4, and it's working very well so far. Thanks!
